### ISSUE TITLE
GLOG_v level does not work correctly

### ISSUE THREAD

**Issue by yehenrytian** [mindspore-ai/mindspore#18]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

> `/device cpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**: 0.1
- **Python version (e.g., Python 3.7.5)**: 3.7.4
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.5 LTS
- **GCC/Compiler version (if compiled from source)**: gcc 5.4

## Describe the current behavior

When I do
```c++
export GLOG_v=2
```
`MS_LOG(INFO)` level information does not show. I have to set the GLOG_v level to exactly 1 to show the INFO level messages

## Describe the expected behavior

Should show INFO level messages at 1 or higher.

## Steps to reproduce the issue
1. bash build.sh -e cpu -z -j32
2. chmod +x build/package/mindspore-0.1.0-cp37-cp37m-linux_x86_64.whl
3. pip install build/package/mindspore-0.1.0-cp37-cp37m-linux_x86_64.whl
4. python pynative1_test.py

## Related log / screenshot
![image](https://user-images.githubusercontent.com/4379480/78304398-a5cdb280-750c-11ea-9e28-0b0b8f48788e.png)

**Comment by fary86** [comment]
Hi yehenrytian,
GLOG provide `LOG` interface to output log, ref `http://rpg.ifi.uzh.ch/docs/glog.html`
GLOG_minloglevel (int, default=0, which is INFO)
Log messages at or above this level. Again, the numbers of severity levels INFO, WARNING, ERROR, and FATAL are 0, 1, 2, and 3, respectively.

The problem is that GLOG `LOG` interface does not provide DEBUG level message, so we use glog's GLOG_v wrapping an new interface `MS_LOG`, the severity levels are 0-DEBUG, 1-INFO, 2-WARNING, 3-ERROR. If you set GLOG_v=1, you can see message of INFO and above, i.e. INFO, WARNING and ERROR.

**Comment by yehenrytian** [comment]
Thanks for the explanation. My misunderstanding.
