### ISSUE TITLE
AttributeError: module 'mindspore.dataset.transforms' has no attribute 'TypeCast'

### ISSUE THREAD

**Issue by sqrk** [mindspore-ai/mindspore#189]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
`/device ascend`</br>

### Software Environment:
- **Python version (e.g., Python 3.7.5)**: Python 3.7.6
- Using ModelArts DevEnviron notebook with **MindSpore-python3.7-aarch64** kernel
- **Work environment**: Ascend-Powered-Engine 1.0 (python3) | Ascend
- **Instance Flavor**: Ascend: 1*Ascend-910(32GB) \| CPU: 24 vCPUs 96GB

## Describe the current behavior
I'm trying to use MindSpore's [CTCModel](https://github.com/mindspore-ai/models/blob/master/research/audio/ctcmodel) (Speech recognition model). When I run the train script, the following error is thrown from the [dataset.py](https://github.com/mindspore-ai/models/blob/master/research/audio/ctcmodel/src/dataset.py) script:
`AttributeError: module 'mindspore.dataset.transforms' has no attribute 'TypeCast'`

In the [docs](https://www.mindspore.cn/docs/en/master/api_python/dataset_transforms/mindspore.dataset.transforms.TypeCast.html) however, it is listed as an attribute.

## Steps to reproduce the issue
In the same ModelArts work environment, run 
``` 
import mindspore.dataset.transforms as C
type_cast_op = C.TypeCast(mstype.int32)
```

## Related log / screenshot
![image](https://user-images.githubusercontent.com/16261327/181052553-d84ea646-d78e-42d1-8553-8ffdc40e1b97.png)

**Comment by JIJIARONGjijiarong** [comment]
May be there is something wrong with your mindspore environment, you can try this command to see your mindspore version.
**pip list | grep mindspore**
If your version is lower than 1.7. You can try to use a higher version like 1.7 or 1.8.
I have tried, and there is no problem with 1.8.
![image](https://user-images.githubusercontent.com/33412538/181217998-43a1835d-a3cc-431a-a5f1-39f43fce2c2b.png)

**Comment by sqrk** [comment]
@JIJIARONGjijiarong I got 
`mindspore-ascend       1.3.0` 
I upgraded to mindspore-ascend 1.8.0 but I'm getting this error 
`libacl_tdt_channel.so: cannot open shared object file: No such file or directory`
which I think is due to the mindspore version not matching the Ascend software but I'm not sure if I can fix that on ModelArts. Do you know anything about it?

**Comment by JIJIARONGjijiarong** [comment]
Yes, this error is due to the mindspore version not matchin the Ascend software.&nbsp;You can contact the manager of the ModelArts to help you solve this problem.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Karima ***@***.***&gt;; 
发送时间: 2022年7月27日(星期三) 晚上9:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mindspore-ai/mindspore] AttributeError: module &#39;mindspore.dataset.transforms&#39; has no attribute &#39;TypeCast&#39; (Issue #189)





 
@JIJIARONGjijiarong I got
 mindspore-ascend       1.3.0
 I upgraded to mindspore-ascend 1.8.0 but I'm getting this error
 libacl_tdt_channel.so: cannot open shared object file: No such file or directory
 which I think is due to the mindspore version not matching the Ascend software but I'm not sure if I can fix that on ModelArts. Do you know anything about it?
