### ISSUE TITLE
Not getting any performance improvement with ms_function

### ISSUE THREAD

**Issue by AlbertAlonso** [mindspore-ai/mindspore#83]
I understant that in order to make use of the optmiziations of mindspore, python functions may need to transform to graph, and that is what `ms_function` does.
>Create a callable MindSpore graph from a python function.
>This allows the MindSpore runtime to apply optimizations based on graph.

However, if I follow[ the example](https://www.mindspore.cn/api/en/master/api/python/mindspore/mindspore.html#mindspore.ms_function) in the documentation using a GPU, I get worse results on microbenchmarks when using `ms_function`

```
import mindspore 
import numpy as np

import mindspore.ops.functional as F
import mindspore.context as context

from mindspore import Tensor, MetaTensor

context.set_context(mode=context.GRAPH_MODE, device_target="GPU")

def tensor_add(x, y):
    z = F.tensor_add(x, y)
    return z

@ms_function
def tensor_add_with_dec(x, y):
    z = F.tensor_add(x, y)
    return z

@ms_function(input_signature=(MetaTensor(mindspore.float32, (1, 1, 3, 3)),
                              MetaTensor(mindspore.float32, (1, 1, 3, 3))))
def tensor_add_with_sig(x, y):
    z = F.tensor_add(x, y)
    return z

x = Tensor(np.ones([1, 1, 3, 3]).astype(np.float32))
y = Tensor(np.ones([1, 1, 3, 3]).astype(np.float32))

tensor_add_graph = ms_function(fn=tensor_add)

%timeit -n10 -r3 out = tensor_add(x, y)
%timeit -n10 -r3 out = tensor_add_graph(x, y)
%timeit -n10 -r3 out = tensor_add_with_dec(x, y)
%timeit -n10 -r3 out = tensor_add_with_sig(x, y)
```
outputs the following results
```
10 loops, best of 3: 113 µs per loop
10 loops, best of 3: 5.45 ms per loop
10 loops, best of 3: 5.28 ms per loop
10 loops, best of 3: 5.3 ms per loop
```

which makes the non-graph function way faster than the others. I would expect `tensor_add_with_sig` to outperform the others. 
Any reason why it is not like that?

**Comment by leonwanghui** [comment]
Hi @AlbertAlonso, although I'm not an expert in performance, could u try to modify the context as below and test it again?
```
context.set_context(mode=context.PYNATIVE_MODE, device_target="GPU")
```
Thanks a lot!

**Comment by AlbertAlonso** [comment]
Hi @leonwanghui, I do get the same benchmarks
```
Context set to Graph
10 loops, best of 3: 105 µs per loop                    # tensor_add
10 loops, best of 3: 5.19 ms per loop                   # tensor_add_graph
10 loops, best of 3: 5.24 ms per loop                   # tensor_add_with_dec
10 loops, best of 3: 5.39 ms per loop                   # tensor_add_with_sig
Context set to PyNative
10 loops, best of 3: 96.8 µs per loop                   # tensor_add
10 loops, best of 3: 5.1 ms per loop                    # tensor_add_graph
10 loops, best of 3: 4.99 ms per loop                   # tensor_add_with_dec
10 loops, best of 3: 5.24 ms per loop                   # tensor_add_with_sig
```

**Comment by Caozhou1995** [comment]
Thanks for your valuable question @AlbertAlonso . @ms_function and ms_function() represents using graph mode and no ms_function means pynative mode in your code. Due to the different implementation of compiling, caching, optimizing and other technologies in two modes, different effects will be achieved in different scenarios.

Pynative mode and graph mode have their own advantages in different scenarios under GPU platform. In this simple single operator scenario, if use the graph mode of ms_function, it will not get any benefits than in pynative mode. But if you run the operator only once, the pynative mode will not be as better as graph mode. When you train deep neural networks, graph mode is faster than pynative mode, and this advantage can be amplified under the Ascend platform.

You can experience the performance advantages of graph mode through resnet50 in model zoo. See in https://github.com/mindspore-ai/mindspore/tree/master/model_zoo/official/cv/resnet.
